[tool.uv.workspace]
members = ["python/*"]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
    "pytest-cov>=6.1.1",
    "testfixtures>=10.0.0",
    "black>=24.10.0",
    "mypy>=1.16.0",
    "ruff>=0.11.12",
    "types-beautifulsoup4>=4.12.0",
    "types-requests>=2.32.0",
    "responses>=0.25.0",
]

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "preserve"

[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
mypy_path = ["python/core/src"]

[[tool.mypy.overrides]]
module = [
    "configurator",
]
ignore_missing_imports = true
